### ISSUE TITLE
Table Navigation Bar in DataGrip weird transparency

### ISSUE THREAD

**Issue by nrsherr2** [jasonhulbert/jetbrains-trash-panda-theme#10]
I don't know the best way to explain in the title what's going on here, so pictures will have to explain what I mean.

![image](https://user-images.githubusercontent.com/51460506/111379398-78c0d400-8679-11eb-8077-d517531856dc.png)
![image](https://user-images.githubusercontent.com/51460506/111379427-824a3c00-8679-11eb-8caa-b2e9d87e7e98.png)
![image](https://user-images.githubusercontent.com/51460506/111379452-8aa27700-8679-11eb-8350-a5bace37acbe.png)
![image](https://user-images.githubusercontent.com/51460506/111379814-ef5dd180-8679-11eb-8c4c-f6f47388fac5.png)
![image](https://user-images.githubusercontent.com/51460506/111380068-4499e300-867a-11eb-89e7-da3be75b1a07.png)

The issue only occurs within the table navigation bar in DataGrip. The `1-XX` and the `of XX+` buttons get lighter and lighter the longer I go without clicking on anything. When I click on something, the lightness goes away. When I hover on any of the other icons on the table navigation bar, the issue spreads to them too, but they do not get brighter like the other two boxes do.

Trash panda is the only non-default theme that is compatible with DataGrip on my machine, so I have no other themes to compare this issue to. Please let me know if this is a JetBrains issue and not just this theme.

Is there a transparency somewhere that isn't properly handled?

**Comment by jasonhulbert** [comment]
This is very weird indeed. I'll have to fire up DataGrip and take a look. Could be a theme compatibility issue but I'm not doing anything special or different with regards to toolbar styles.

Thanks for reporting.

**Comment by nrsherr2** [comment]
Hey Jason, thanks for fixing this! Sorry I'm a little late with the response, but everything is great!
