### ISSUE TITLE
UI Glitches on Hover

### ISSUE THREAD

**Issue by brianebeling** [jasonhulbert/jetbrains-trash-panda-theme#14]
When hovering certain elements, like options my UI glitches like that. Is that a known issue? Or do you know why that could happen? Maybe its a configuration thing.

[Example](https://i.imgur.com/4jcCsLm.png)

**Comment by jasonhulbert** [comment]
@brianebeling I haven't experienced this issue. My first guess would be it has something to do with the custom, monospaced font you're using in your appearance settings.

It might be worth trying to reset the UI font to Jetbrains default and see if the issue persists. "Appearance & Behavior" -> "Appearance" -> (Uncheck) "Use custom font"

**Comment by jasonhulbert** [comment]
You could also post this issue on [YouTrack](https://youtrack.jetbrains.com/issues)

**Comment by bslote** [comment]
It happens to me as well. No custom font being used (or any setting that would otherwise override the default appearance). I can also confirm that it happens in both Rider and IntelliJ IDEA (2022.2.2). The buggy behavior started happening with the Trash Panda 2.0.0 update.

**Comment by jasonhulbert** [comment]
I’ll look into it further but I’m not sure how to recreate the issue. Have you seen this with other themes? Would you mind trying?

**Comment by brianebeling** [comment]
Hi Jason, first of all, thank for you for the theme. I love it.

Trying the things you mentioned yielded no luck unfortunately. I'll wait a bit with the YouTrack ticket for now. Maybe we can collect some data to find a possible cause.

My current setup is:
Windows 11,
Up 2 date rider,
i5 8600k,
MSI RTX 3080


This is personally the first time I've seen a theme do that. I'm very curious as to what could be the issue.

**Comment by Riaan-Crause-Kohde** [comment]
Don't know if this might be of any use, but it seems to "cache" and render something that was recently hovered over in the back. It doesn't seem completely random to me as mentioned above.

![Animation](https://user-images.githubusercontent.com/33822243/197556991-bf579a0f-8720-495e-a887-2562b02462ed.gif)

**Comment by brianebeling** [comment]
Interestingly the issue is not present on the new EAP versions when the Beta UI is enabled

**Comment by jasonhulbert** [comment]
@brianebeling @Riaan-Crause-Kohde 

One of the differences on the Button components compared to other UI components is that, in some cases, I'm using a transparent background instead of a defined color. I changed those transparent values to be the same as the default background color. In order to allow you to test it out and see if it resolves this issue, I published a beta version (2.0.2-beta.1) to the marketplace yesterday. Would you guys mind downloading/installing that beta version and let me know if the issue persists?

<img width="961" alt="Screen Shot 2022-11-01 at 1 54 14 PM" src="https://user-images.githubusercontent.com/1451375/199304458-64db509b-cefc-47d5-9998-98650c7186bd.png">

**Comment by jasonhulbert** [comment]
> No change, concerning the glitching, with the beta for me. Thank you for trying, though!

Thanks for checking @brianebeling

**Comment by DiegoLpVn** [comment]
Same problem is happening to me in both Android Studio and IntelliJ.
I've tried switching different Appearance settings but nothing seems to fix the glitch.

That does not only happen when hovering but also when pressing "Alt" key on Windows.

If it helps, it only (or mainly) seems to happen when using Dialogs.
For example if I open the Git Commit Dialog, every checkbox glitches when hovering or pressing Alt, but if I open it on "non-modal window" the checkbox doesn't seem to glitch.

**Comment by jasonhulbert** [comment]
As far as I can tell, this issue is resolved. If anyone else encounters the issue after updating to IDE build version >= 231.* and plugin version >= 2.0.4, please let me know.
