### ISSUE TITLE
Current file in Project View is not highlighted

### ISSUE THREAD

**Issue by idanski** [jasonhulbert/jetbrains-trash-panda-theme#15]
In most other themes I'm able to discern the current file in project view as it is highlighted.

I think in this case the color is maybe the same color as the background?

EDIT: It is shown as blue when the project view is in focus, but not when the focus is on the editor.
Using GoLand 2022.2.2.

**Comment by jasonhulbert** [comment]
This has been addressed as part of the v2.0.1 updates - which will be publicly available once approved by jetbrains marketplace.
