### ISSUE TITLE
[BUG?] Methods Overloads Auto Complete Popup Shows White Color

### ISSUE THREAD

**Issue by HGGamers** [jasonhulbert/jetbrains-trash-panda-theme#32]
I'm not sure if this is intentional or a bug, but the Method Overload popup? shows a white color for the currently selected method. I have attached a screenshot. I am using Rider 2023.1.3 with the new user interface enabled. Theme: Normal not Moonlight or Highcontrast. But it looks the same with the others.

![Screenshot](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/18753034/86e3888e-8454-465a-8320-96ed7df911cb)

Thanks for the theme, I like it :)

**Comment by jasonhulbert** [comment]
I haven't been able to reproduce this. Will close unless someone can recreate the issue with the latest version. Thank you.

**Comment by HGGamers** [comment]
Can confirm that it is no longer in the latest version:
![Screenshot 2024-01-02 164201](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/18753034/5f6783dd-9b28-439c-98a1-d92a02603b09)

However, I have now noticed that if you only write 'Console.Wr' for example, and then wait for the next popup, it still appears:
![Screenshot 2024-01-02 164406](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/18753034/130feb72-1e01-4569-a0ca-3edb65d7e6e7)
