### ISSUE TITLE
[Suggestion] Different color for Memory Indicator in status bar

### ISSUE THREAD

**Issue by HGGamers** [jasonhulbert/jetbrains-trash-panda-theme#33]
With the current color it is a bit difficult to read. Maybe another color combination so that it is easier to read?

![Test2](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/18753034/09fd64e3-ef5e-4f9b-91a0-082c06d17cba)

**Comment by jasonhulbert** [comment]
#49

**Comment by jasonhulbert** [comment]
Will be available in v2.0.8 when the update is approved on marketplace (1-2 days)

**Comment by jasonhulbert** [comment]
<img width="117" alt="Screenshot 2024-01-02 at 10 41 55 AM" src="https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/1451375/89f85213-30e1-4b85-ab2f-a157f68abf99">
