### ISSUE TITLE
[BUG] 2.0.6 (2023.08.01) in Webstorm 2023.1.4 

### ISSUE THREAD

**Issue by kacyrogers** [jasonhulbert/jetbrains-trash-panda-theme#36]
2.0.6 [standard] theme is not working (correctly?) in WS. High contrast, moonlight, and light all appear normal. Also, It's working fine in Pycharm.

My IDE currently: 

![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/54042531/9f427aa4-fff4-40d8-a4b1-0f8465b51ab0)

![Capture](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/54042531/1f27b3d9-1883-492f-bcff-85c8f149eaf7)

**Comment by jasonhulbert** [comment]
I encountered this same issue. I’m not sure this is something I can address as a bug but I will figure out the steps needed to clear cached plugin assets in the ide. Thank you for reporting.

**Comment by SylvanasCry** [comment]
The same in GoLand 2023.2. Even if you remove the plugin, the error persists.

**Comment by jasonhulbert** [comment]
Resolved in #45
