### ISSUE TITLE
Weird graphical effects

### ISSUE THREAD

**Issue by Arcalise08** [jasonhulbert/jetbrains-trash-panda-theme#38]
It seems there are some weird effects happening when using this theme. Swapping themes fixes it.  

![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/61042848/ce9642aa-4daa-44f6-b702-0a1043248485)

Found in 2023.2.2

**Comment by jasonhulbert** [comment]
@Arcalise08 Which version of the plugin are you using? I've had others report a similar issue in the past, but I was under the impression it was resolved. https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/28

**Comment by jasonhulbert** [comment]
#49

**Comment by jasonhulbert** [comment]
Will be available in v2.0.8 when the update is approved on marketplace (1-2 days)

**Comment by Arcalise08** [comment]
Sorry i didnt see your question before. We were away on holiday. I was using the latest version of it available on the marketplace. Sounds like you got it figured out though. Thank you!
