### ISSUE TITLE
Version 233 compatibility

### ISSUE THREAD

**Issue by NinoFloris** [jasonhulbert/jetbrains-trash-panda-theme#39]
Trying to install 2.0.6 from disk on Rider gives

> Plugin 'Trash Panda Theme' (version '2.0.6') is not compatible with the current version of the IDE, because it requires build 232.* or older but the current build is RD-233.11799.261

**Comment by jmatthiesen81** [comment]
The strange behaviour that version 1.6 of the Trash Panda Theme will be installed for 2023.3 due to the configured compatibility range `191+` made me smile. :see_no_evil:

**Comment by nul800sebastiaan** [comment]
I've added a PR to bump the version. 

The attached zip file works for now as a manual install (might need to remove the previous version first and restart the IDE.

However I can see that the IDE's "chrome" is very gray now, where it previously was black, before:

![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/304656/9b0d8ed3-0059-46fd-a944-897339ccc57d)

After:

![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/304656/2a91ba48-7b80-46cd-a5ea-e99d54f24421)

Not sure if that is a Panda theme problem, or me hacking the zip file, or a Jetbrains problem.

[Uploading jetbrains-trash-panda-theme-2.0.7.zip…]()

**Comment by jmatthiesen81** [comment]
Like @Ran-Mewo wrote [here](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/40#issuecomment-1846863899) before manually editing the build range doesn't fix the issue. Parts of the theme are still broken. Until the theme will be fixed I decided to use another one (One Dark italic).
