### ISSUE TITLE
The new update of the PhpStorm 2023.3 broke the color theme for me.

### ISSUE THREAD

**Issue by lukasz-kapica** [jasonhulbert/jetbrains-trash-panda-theme#40]
Is anybody experiencing the same issue?

**Comment by bryan-a-clark** [comment]
I was using Trash Panda Theme(moonlight), but I don't see that listed anymore.

**Comment by Ran-Mewo** [comment]
not really the full issue
I tried manually editing the build range for 2.0.6 to make intellij think it works for 2023.3 and install that but the color schemes were still broken

seems like the plugin needs to be actually fixed for this version
I hope they fix it soon I really love this theme

**Comment by vimalrocker** [comment]
JetBrains Rider 2023.3 version broke the theme
