### ISSUE TITLE
The new update of the Rider 2023.3 broke the color theme for me.

### ISSUE THREAD

**Issue by vimalrocker** [jasonhulbert/jetbrains-trash-panda-theme#41]
After updating Rider to the new  Build #RD-233.11799.261  Theme stopped working  for me

**Comment by vimalrocker** [comment]
Is this issue fixed and pushed any update

**Comment by nul800sebastiaan** [comment]
@vimalrocker I'd recommend closing this redudant issue and following issue #39 - give the theme author some time, they might be very busy with other things.
