### ISSUE TITLE
Latest theme is broken after current update

### ISSUE THREAD

**Issue by forscht** [jasonhulbert/jetbrains-trash-panda-theme#43]

**Comment by jasonhulbert** [comment]
https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/44#issuecomment-1861231617

**Comment by jasonhulbert** [comment]
https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/44#issuecomment-1864764942

**Comment by jasonhulbert** [comment]
Published 2.0.7 to the marketplace which should resolve this issue. Pending approval which usually takes a day or two.
