### ISSUE TITLE
Extra space between tree items compared to other themes.

### ISSUE THREAD

**Issue by forscht** [jasonhulbert/jetbrains-trash-panda-theme#46]
Recent update broke the UI, now there is extra space between tree items compared to other themes which makes it look bad.
Dracula Theme
![tree-dracula](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/59018146/097742d7-4468-4562-959d-f7379628c4ce)

Trash Panda Theme
![tree-trash-panda](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/59018146/c7547fb7-8493-45ff-8792-410cd84e7d88)

**Comment by jasonhulbert** [comment]
@forscht The row height on tree menus was not updated - it has always been set to a higher value than default. It's likely that you previously had a personal setting for this that was not restored after an IDE update. A number of issues were reported on JetBrains YouTrack related to this problem and I'm not sure if that's been resolved yet.

Here is where the row height is set in the theme files:
https://github.com/jasonhulbert/jetbrains-trash-panda-theme/blob/master/src/main/resources/trash-panda-theme.theme.json#L411C5-L411C28

As you can see, it has not changed. I prefer a little more space between tree items. If your _preference_ is to have a more compact appearance, I suggest trying the "Compact mode" in the "Appearance & Behavior -> Appearance -> New UI" settings.
