### ISSUE TITLE
First item in autocomplete popup isn't selected by default

### ISSUE THREAD

**Issue by lukef** [jasonhulbert/jetbrains-trash-panda-theme#47]
**IntelliJ IDEA 2023.3.2 (Ultimate Edition)**
Build #IU-233.13135.103, built on December 19, 2023
Linux 6.6.8-200.fc39.x86_64
Current Desktop: GNOME

-------

When the autocomplete popup opens, the first item appears deselected. If you press `Enter`, the first item will be chosen. If you hit `Down Arrow`, the second item will be highlighted.

Default selection:
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/37941/5690c0c8-1cc5-42b5-8c08-a99fd0b14e59)

Pressing `Down Arrow`:
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/37941/c69e68f2-0f01-4e66-b0c2-a9dbcf0b377e)

**Comment by jasonhulbert** [comment]
Thanks @lukef - will be addressed in the next release

**Comment by jasonhulbert** [comment]
#49

**Comment by jasonhulbert** [comment]
Will be available in v2.0.8 when the update is approved on marketplace (1-2 days)
