### ISSUE TITLE
Scrollbar color on Windows is TOO Bright

### ISSUE THREAD

**Issue by harveywong98** [jasonhulbert/jetbrains-trash-panda-theme#5]
Hello! I really like this theme.😁
But on my windows computer, the scrollbar where on the Project Tree is TOO Bright. May you let the scrollbar color to a more dark one? Thank you 😘.

**Comment by jasonhulbert** [comment]
@harveywong98 - Thank you. I update to the scrollbar color in branch v1.5 and it will get published this week.

**Comment by harveywong98** [comment]
> @harveywong98 - Thank you. I update to the scrollbar color in branch v1.5 and it will get published this week.

Thanks🥳

**Comment by jasonhulbert** [comment]
Published.
