### ISSUE TITLE
Broken theme in Rider with new update 2.0.8

### ISSUE THREAD

**Issue by thatsBruno** [jasonhulbert/jetbrains-trash-panda-theme#50]
After the new update (2.0.8) the standard Trash Panda Theme theme broke.
Version: Rider 2023.3.2

![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/28793603/a3ff2acb-f60e-4f85-83cc-fcad74581857)

**Comment by jasonhulbert** [comment]
@thatsBruno Are you able to go to "Editor -> Color Scheme" and select the correct color scheme?

**Comment by thatsBruno** [comment]
Seems to have worked, thanks!

**Comment by jasonhulbert** [comment]
Great - thank you @thatsBruno
