### ISSUE TITLE
Rider Update to 2023.3.2 broke the theme 

### ISSUE THREAD

**Issue by vimalrocker** [jasonhulbert/jetbrains-trash-panda-theme#51]
After  the  Rider update to version 2023.3.2 has caused the theme to break. The theme is not getting applied properly

**Comment by jasonhulbert** [comment]
@vimalrocker https://github.com/jasonhulbert/jetbrains-trash-panda-theme/issues/50#issuecomment-1875409526

Try selecting the corresponding color scheme (as mentioned in the above comment).

**Comment by vimalrocker** [comment]
Thanks @jasonhulbert it worked.
