### ISSUE TITLE
Inspection Bar Font Color

### ISSUE THREAD

**Issue by TheWrightDev** [jasonhulbert/jetbrains-trash-panda-theme#52]
Is there a way to change the font color of the little inspection popup?
Very hard to read the number without hovering.

Normal:
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/6202690/69517f65-8b47-4fca-8aed-cdea5ff3f72c)

Hovering:
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/6202690/f3e763f9-99bd-410e-9f8a-e29b6115bee7)

**Comment by jasonhulbert** [comment]
@TheWrightDev  Where is this shown in the inspection popup? Would you mind adding a more complete screen grab please?

Sometimes the IDE retains artifacts from the previously applied theme. Did you try restarting the IDE after switching themes?  If not, might be worth a try.

**Comment by TheWrightDev** [comment]
It's in the upper right corner of the editor. I tried restarting as well as changing back to the stock theme (where the text is light and readable) and then back to trash panda where it becomes difficult again
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/6202690/f19c2eaa-8daf-4660-85b5-cf2ed38889fe)

**Comment by jasonhulbert** [comment]
Hey @TheWrightDev - this has been fixed in the 2.1.0 release which will be availabe for download/update on the marketplace in 1-2 days. Thanks for reporting.
