### ISSUE TITLE
Undistinguishable caret row background color for the High Contrast Scheme

### ISSUE THREAD

**Issue by brokenthorn** [jasonhulbert/jetbrains-trash-panda-theme#53]
The high contrast scheme specifies the same background color for the caret row as the general editor background, making the current line highlight not distinguishable on the editor:
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/2119004/d5c195e4-29f5-485e-8642-39500366a16e)

Here is the default scheme for contrast:
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/2119004/e4831ddd-da03-4d8a-b48f-ad1277b4d7d7)

Can I suggest to use the same color as the default scheme (LGTM):
![image](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/2119004/ca60dfcf-8bb0-4e1d-adec-a3ba117215ea)

**Comment by jasonhulbert** [comment]
Hey @brokenthorn - as mentioned in the other issue the improved "Blacklight" high contrast theme improves this by using a dark, modified variant of the blue accent color for caret row background. Thanks again for reporting.
