### ISSUE TITLE
For selected parameter is not displayed where is used (Goland 2024.1)

### ISSUE THREAD

**Issue by dpcat237** [jasonhulbert/jetbrains-trash-panda-theme#55]
**What steps will reproduce the issue?**
1. Select a parameter inside of some scope such as a function.

**What is the expected result?**
Marked where is used selected parameter inside of the scope.

**What happens instead?**
Is not marked where is used selected parameter inside of the scope.
The affected version is Goland 2024.1. I attached also an example from Goland 2023.3 where this works well. For default themes in Goland 2024.1, this issue is not reproducible.

PS. It's interesting that between the Goland versions, the same theme has different colors.

![Goland2023 3](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/388031/bff180b4-dcd3-4b91-a2d8-e046f5b27945)
![Goland2024 1](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/388031/c7335539-35b8-4266-95ad-4074ff783dd5)
[idea-Goland2023.3.log](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/files/14903594/idea-Goland2023.3.log)
[idea-Goland2024.1.log](https://github.com/jasonhulbert/jetbrains-trash-panda-theme/files/14903595/idea-Goland2024.1.log)

**Comment by jasonhulbert** [comment]
Hey @dpcat237 - the difference in theme colors is due to the ide falling back to a significantly older version of the theme after the 2024.* release of jetbrains products. I just published 2.1.0 version of the plugin to the marketplace and it will be available for download in 1-2 days after review.

Thank you!
