### ISSUE TITLE
Moonlight Background in tab has light theme in DataGrip

### ISSUE THREAD

**Issue by koalazub** [jasonhulbert/jetbrains-trash-panda-theme#58]
<img width="1284" alt="image" src="https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/7111524/7fadcfa4-c2ac-47cb-b255-73b9f1645eb0">

Daylight, Blacklight, Dawnlight and Trash Panda are just fine

**Comment by jasonhulbert** [comment]
@koalazub You need to set the corresponding "Color Scheme" which is distinct from the UI "Theme". Unfortunately, jetbrains IDEs sometimes do not automatically select the correct, corresponding "Color Scheme" when switching the "Theme".

Depending on the IDE version you are using, you'll be able to change the "Color Theme" in one of two places:

In "Appearance & Behavior" -> "Appearance" -> "Editor Color Scheme"

<img width="550" alt="Screenshot 2024-05-22 at 8 29 05 AM" src="https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/1451375/91fa065b-8d3d-4b2a-aee1-ac0f5680baa3">

Or, in "Editor -> "Color Scheme" -> "Scheme"

<img width="590" alt="Screenshot 2024-05-22 at 8 29 18 AM" src="https://github.com/jasonhulbert/jetbrains-trash-panda-theme/assets/1451375/be107984-3fa2-48c7-a04e-4b7be107b58b">

**Comment by koalazub** [comment]
Ah! I should've checked that. I'm using the DataGrip EAP and didn't think that there'd be a bug when switching between those two themes. 

Thanks for pointing that out
