### ISSUE TITLE
It seems compatibility broke with version 2024.2.0.1 of Intellij.

### ISSUE THREAD

**Issue by thecodemonk** [jasonhulbert/jetbrains-trash-panda-theme#61]
Just like in issue #44 none of the themes are showing and the plugin is version 1.6. I've tried uninstalling and reinstalling the plugin and it still is only showing version 1.6.

**Comment by lukasz-kapica** [comment]
It happens every major update.

**Comment by jasonhulbert** [comment]
Sorry about that - published a compatibility update and hopefully it will get approved later today.

**Comment by jasonhulbert** [comment]
Published compatible version (2.2.1)
