### ISSUE TITLE
WebStorm 2019.3 styled-components (template literals) syntax is not highlighted

### ISSUE THREAD

**Issue by l3v1k** [jasonhulbert/jetbrains-trash-panda-theme#7]
After I've updated webstorm to ver. 2019.3 the theme's colors had stopped work on template literals. I've been checking both styled-components plugin and this amazing theme, and when I switched it to Darcula (default night theme) -- everything worked as expected.
![image](https://user-images.githubusercontent.com/6277287/70320148-b0ad5a80-182c-11ea-9a96-b6ba6eca881d.png)

Darcula: 
![Screen Shot 2019-12-06 at 13 34 12](https://user-images.githubusercontent.com/6277287/70320351-21ed0d80-182d-11ea-8d54-871a3fc2d17a.png)

Also I've asked one of my friends to check this and same happens to him.

**Comment by jasonhulbert** [comment]
Thanks for reporting and sorry for the delayed response. I’ve been on vacation. I’ll get this resolved and published tomorrow.

**Comment by jasonhulbert** [comment]
This should be resolved as injected language fragments now have explicit color scheme settings
