### ISSUE TITLE
Support Identifier under caret color

### ISSUE THREAD

**Issue by chamisf** [jasonhulbert/jetbrains-trash-panda-theme#8]
Please add theme support to the following sections for both background and error stipe mark.

- Identifier under caret 
- Identifier under caret (write)

I've created mine but should be able to improve.

![image](https://user-images.githubusercontent.com/10853008/90948813-2eb79d00-e460-11ea-8e63-0f68391e6bc5.png)

**Comment by jasonhulbert** [comment]
@chamisf Fixed and released. Thanks and sorry for the delay - I'm giving the plugin some needed attention.
